FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
COPY apps/backend/package.json ./apps/backend/
COPY packages/shared/package.json ./packages/shared/

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm --filter @salary/shared build
RUN pnpm --filter backend exec prisma generate
RUN pnpm --filter backend build

EXPOSE 4000

CMD ["pnpm", "--filter", "backend", "start"]